.TH chopin 1 dwm\-VERSION
.SH NAME
chopin \- A cli tool that greatly improves your work efficiency.
.SH SYNOPSIS
.B chopin
.RB [ \-vhoecmr ]
.RB file
.SH DESCRIPTION
chopin is a tool for cli to open, exec, cp, mv, rm file automatically.
.P
.SH OPTIONS
.TP
.B \-v
prints version information to cli and exit.
.TP
.B \-h
help manual.
.TP
.B \-o
open a file with your default settings automatically.
.TP
.B \-e
exec a script with your default settings automatically.
.TP
.B \-c
copy a file.
.TP
.B \-m
move a file.
.TP
.B \-r
remove a file.
.SH CUSTOMIZATION
chopin is customized by creating a custom config.h and recompiling the source code. This
keeps it fast, secure and simple.
.SH BUGS
Send all bug reports with a patch to zetatez@icloud.com.
